// GENERATED by `npm run sync:audio`. Do not edit by hand.
// Lists the audio files found in public/audio and their measured lengths.

export type AudioFile = { src: string; seconds: number };

export type AudioManifest = {
  // "<sceneId>/<cueId>": one recorded narration line
  lines: Record<string, AudioFile>;
  // "<sceneId>": one recording covering a whole scene
  scenes: Record<string, AudioFile>;
  // "<slotId>": background music for a music slot
  music: Record<string, AudioFile>;
};

export const AUDIO_MANIFEST: AudioManifest = {
  "lines": {},
  "scenes": {},
  "music": {}
};
