// Generated by `npm run sync:audio`. Do not edit by hand.

export type AudioFile = { src: string; seconds: number };
export type AudioManifest = {
  lines: Record<string, AudioFile>;
  music: Record<string, AudioFile>;
  sfx: Record<string, AudioFile>;
};

export const AUDIO_MANIFEST: AudioManifest = {
  "lines": {
    "coldOpen/accusation": {
      "src": "audio/voiceover/coldOpen/accusation.mp3",
      "seconds": 3.213
    },
    "coldOpen/centre": {
      "src": "audio/voiceover/coldOpen/centre.mp3",
      "seconds": 6.322
    },
    "coldOpen/date": {
      "src": "audio/voiceover/coldOpen/date.mp3",
      "seconds": 4.362
    },
    "coldOpen/glass": {
      "src": "audio/voiceover/coldOpen/glass.mp3",
      "seconds": 3.683
    },
    "coldOpen/name": {
      "src": "audio/voiceover/coldOpen/name.mp3",
      "seconds": 2.743
    },
    "coldOpen/notices": {
      "src": "audio/voiceover/coldOpen/notices.mp3",
      "seconds": 4.78
    },
    "coldOpen/officer": {
      "src": "audio/voiceover/coldOpen/officer.mp3",
      "seconds": 4.65
    },
    "coldOpen/sediment": {
      "src": "audio/voiceover/coldOpen/sediment.mp3",
      "seconds": 1.541
    },
    "coldOpen/sips": {
      "src": "audio/voiceover/coldOpen/sips.mp3",
      "seconds": 1.959
    },
    "coldOpen/suspects": {
      "src": "audio/voiceover/coldOpen/suspects.mp3",
      "seconds": 1.985
    },
    "coldOpen/throws": {
      "src": "audio/voiceover/coldOpen/throws.mp3",
      "seconds": 2.22
    },
    "coldOpen/wrong": {
      "src": "audio/voiceover/coldOpen/wrong.mp3",
      "seconds": 2.142
    },
    "phayre/building": {
      "src": "audio/voiceover/phayre/building.mp3",
      "seconds": 3.265
    },
    "phayre/complicated": {
      "src": "audio/voiceover/phayre/complicated.mp3",
      "seconds": 3.265
    },
    "phayre/gaekwad": {
      "src": "audio/voiceover/phayre/gaekwad.mp3",
      "seconds": 4.362
    },
    "phayre/notDiplomat": {
      "src": "audio/voiceover/phayre/notDiplomat.mp3",
      "seconds": 2.978
    },
    "phayre/notStory": {
      "src": "audio/voiceover/phayre/notStory.mp3",
      "seconds": 4.336
    },
    "phayre/resident": {
      "src": "audio/voiceover/phayre/resident.mp3",
      "seconds": 3.527
    },
    "phayre/role": {
      "src": "audio/voiceover/phayre/role.mp3",
      "seconds": 7.497
    },
    "phayre/strained": {
      "src": "audio/voiceover/phayre/strained.mp3",
      "seconds": 6.504
    },
    "barodaConflict/concerns": {
      "src": "audio/voiceover/barodaConflict/concerns.mp3",
      "seconds": 7.053
    },
    "barodaConflict/deteriorated": {
      "src": "audio/voiceover/barodaConflict/deteriorated.mp3",
      "seconds": 5.251
    },
    "barodaConflict/grievances": {
      "src": "audio/voiceover/barodaConflict/grievances.mp3",
      "seconds": 5.512
    },
    "barodaConflict/hostile": {
      "src": "audio/voiceover/barodaConflict/hostile.mp3",
      "seconds": 5.407
    },
    "barodaConflict/inquiry": {
      "src": "audio/voiceover/barodaConflict/inquiry.mp3",
      "seconds": 6.139
    },
    "barodaConflict/phayreBelieved": {
      "src": "audio/voiceover/barodaConflict/phayreBelieved.mp3",
      "seconds": 5.068
    },
    "barodaConflict/then": {
      "src": "audio/voiceover/barodaConflict/then.mp3",
      "seconds": 1.776
    },
    "poisoning/discarded": {
      "src": "audio/voiceover/poisoning/discarded.mp3",
      "seconds": 2.508
    },
    "poisoning/drank": {
      "src": "audio/voiceover/poisoning/drank.mp3",
      "seconds": 1.149
    },
    "poisoning/examined": {
      "src": "audio/voiceover/poisoning/examined.mp3",
      "seconds": 3.109
    },
    "poisoning/found": {
      "src": "audio/voiceover/poisoning/found.mp3",
      "seconds": 4.441
    },
    "poisoning/morning": {
      "src": "audio/voiceover/poisoning/morning.mp3",
      "seconds": 4.258
    },
    "poisoning/nausea": {
      "src": "audio/voiceover/poisoning/nausea.mp3",
      "seconds": 4.545
    },
    "poisoning/noticed": {
      "src": "audio/voiceover/poisoning/noticed.mp3",
      "seconds": 3.918
    },
    "poisoning/ready": {
      "src": "audio/voiceover/poisoning/ready.mp3",
      "seconds": 3.318
    },
    "poisoning/reported": {
      "src": "audio/voiceover/poisoning/reported.mp3",
      "seconds": 5.303
    },
    "investigation/access": {
      "src": "audio/voiceover/investigation/access.mp3",
      "seconds": 6.113
    },
    "investigation/arrest": {
      "src": "audio/voiceover/investigation/arrest.mp3",
      "seconds": 7.079
    },
    "investigation/connection": {
      "src": "audio/voiceover/investigation/connection.mp3",
      "seconds": 5.486
    },
    "investigation/difficult": {
      "src": "audio/voiceover/investigation/difficult.mp3",
      "seconds": 2.664
    },
    "investigation/pelly": {
      "src": "audio/voiceover/investigation/pelly.mp3",
      "seconds": 7.549
    },
    "investigation/questioned": {
      "src": "audio/voiceover/investigation/questioned.mp3",
      "seconds": 4.206
    },
    "investigation/testimony": {
      "src": "audio/voiceover/investigation/testimony.mp3",
      "seconds": 6.504
    },
    "investigation/who": {
      "src": "audio/voiceover/investigation/who.mp3",
      "seconds": 2.795
    },
    "accusation/attacked": {
      "src": "audio/voiceover/accusation/attacked.mp3",
      "seconds": 3.918
    },
    "accusation/certainty": {
      "src": "audio/voiceover/accusation/certainty.mp3",
      "seconds": 3.474
    },
    "accusation/connect": {
      "src": "audio/voiceover/accusation/connect.mp3",
      "seconds": 4.362
    },
    "accusation/household": {
      "src": "audio/voiceover/accusation/household.mp3",
      "seconds": 8.046
    },
    "accusation/moreThanOnce": {
      "src": "audio/voiceover/accusation/moreThanOnce.mp3",
      "seconds": 6.243
    },
    "accusation/notSimply": {
      "src": "audio/voiceover/accusation/notSimply.mp3",
      "seconds": 5.016
    },
    "accusation/other": {
      "src": "audio/voiceover/accusation/other.mp3",
      "seconds": 6.296
    },
    "defence/assembled": {
      "src": "audio/voiceover/defence/assembled.mp3",
      "seconds": 5.851
    },
    "defence/ballantine": {
      "src": "audio/voiceover/defence/ballantine.mp3",
      "seconds": 8.829
    },
    "defence/british": {
      "src": "audio/voiceover/defence/british.mp3",
      "seconds": 6.191
    },
    "defence/crossExam": {
      "src": "audio/voiceover/defence/crossExam.mp3",
      "seconds": 5.486
    },
    "defence/denied": {
      "src": "audio/voiceover/defence/denied.mp3",
      "seconds": 3.109
    },
    "defence/indian": {
      "src": "audio/voiceover/defence/indian.mp3",
      "seconds": 6.087
    },
    "defence/instigated": {
      "src": "audio/voiceover/defence/instigated.mp3",
      "seconds": 6.374
    },
    "defence/moreThan": {
      "src": "audio/voiceover/defence/moreThan.mp3",
      "seconds": 4.571
    },
    "defence/press": {
      "src": "audio/voiceover/defence/press.mp3",
      "seconds": 4.127
    },
    "defence/remarkable": {
      "src": "audio/voiceover/defence/remarkable.mp3",
      "seconds": 3.918
    },
    "commission/divided": {
      "src": "audio/voiceover/commission/divided.mp3",
      "seconds": 2.064
    },
    "commission/fascinating": {
      "src": "audio/voiceover/commission/fascinating.mp3",
      "seconds": 4.963
    },
    "commission/noUnanimous": {
      "src": "audio/voiceover/commission/noUnanimous.mp3",
      "seconds": 2.377
    },
    "commission/notProved": {
      "src": "audio/voiceover/commission/notProved.mp3",
      "seconds": 5.355
    },
    "commission/prove": {
      "src": "audio/voiceover/commission/prove.mp3",
      "seconds": 5.799
    },
    "commission/proved": {
      "src": "audio/voiceover/commission/proved.mp3",
      "seconds": 3.37
    },
    "commission/wasPoison": {
      "src": "audio/voiceover/commission/wasPoison.mp3",
      "seconds": 3.579
    },
    "deposition/control": {
      "src": "audio/voiceover/deposition/control.mp3",
      "seconds": 4.963
    },
    "deposition/deposed": {
      "src": "audio/voiceover/deposition/deposed.mp3",
      "seconds": 4.258
    },
    "deposition/despite": {
      "src": "audio/voiceover/deposition/despite.mp3",
      "seconds": 4.78
    },
    "deposition/exile": {
      "src": "audio/voiceover/deposition/exile.mp3",
      "seconds": 5.669
    },
    "deposition/grounds": {
      "src": "audio/voiceover/deposition/grounds.mp3",
      "seconds": 5.669
    },
    "deposition/larger": {
      "src": "audio/voiceover/deposition/larger.mp3",
      "seconds": 7.34
    },
    "deposition/notPoisoning": {
      "src": "audio/voiceover/deposition/notPoisoning.mp3",
      "seconds": 4.728
    },
    "deposition/separate": {
      "src": "audio/voiceover/deposition/separate.mp3",
      "seconds": 5.251
    },
    "assessment/accused": {
      "src": "audio/voiceover/assessment/accused.mp3",
      "seconds": 2.351
    },
    "assessment/confidence": {
      "src": "audio/voiceover/assessment/confidence.mp3",
      "seconds": 3.135
    },
    "assessment/deposed": {
      "src": "audio/voiceover/assessment/deposed.mp3",
      "seconds": 2.534
    },
    "assessment/divided": {
      "src": "audio/voiceover/assessment/divided.mp3",
      "seconds": 2.064
    },
    "assessment/followed": {
      "src": "audio/voiceover/assessment/followed.mp3",
      "seconds": 5.224
    },
    "assessment/matters": {
      "src": "audio/voiceover/assessment/matters.mp3",
      "seconds": 2.09
    },
    "assessment/readings": {
      "src": "audio/voiceover/assessment/readings.mp3",
      "seconds": 4.807
    },
    "assessment/reported": {
      "src": "audio/voiceover/assessment/reported.mp3",
      "seconds": 4.362
    },
    "assessment/separate": {
      "src": "audio/voiceover/assessment/separate.mp3",
      "seconds": 6.635
    },
    "assessment/uncontested": {
      "src": "audio/voiceover/assessment/uncontested.mp3",
      "seconds": 7.027
    },
    "assessment/what": {
      "src": "audio/voiceover/assessment/what.mp3",
      "seconds": 3.213
    },
    "ending/intervene": {
      "src": "audio/voiceover/ending/intervene.mp3",
      "seconds": 4.415
    },
    "ending/oneGlass": {
      "src": "audio/voiceover/ending/oneGlass.mp3",
      "seconds": 7.053
    },
    "ending/power": {
      "src": "audio/voiceover/ending/power.mp3",
      "seconds": 2.717
    },
    "ending/struggle": {
      "src": "audio/voiceover/ending/struggle.mp3",
      "seconds": 4.127
    }
  },
  "music": {
    "courtroom": {
      "src": "audio/music/courtroom.mp3",
      "seconds": 69.251
    },
    "ending": {
      "src": "audio/music/ending.mp3",
      "seconds": 169.535
    },
    "investigation": {
      "src": "audio/music/investigation.mp3",
      "seconds": 246.465
    },
    "opening": {
      "src": "audio/music/opening.mp3",
      "seconds": 20.872
    },
    "title": {
      "src": "audio/music/title.mp3",
      "seconds": 21.838
    },
    "verdict": {
      "src": "audio/music/verdict.mp3",
      "seconds": 47.647
    }
  },
  "sfx": {
    "carriage": {
      "src": "audio/sfx/carriage.mp3",
      "seconds": 8.046
    },
    "city": {
      "src": "audio/sfx/city.mp3",
      "seconds": 12.042
    },
    "courtroom": {
      "src": "audio/sfx/courtroom.mp3",
      "seconds": 69.251
    },
    "door": {
      "src": "audio/sfx/door.mp3",
      "seconds": 5.042
    },
    "footsteps": {
      "src": "audio/sfx/footsteps.mp3",
      "seconds": 4.232
    },
    "glass-set": {
      "src": "audio/sfx/glass-set.mp3",
      "seconds": 1.646
    },
    "glass-throw": {
      "src": "audio/sfx/glass-throw.mp3",
      "seconds": 2.247
    },
    "morning": {
      "src": "audio/sfx/morning.mp3",
      "seconds": 10.031
    },
    "palace": {
      "src": "audio/sfx/palace.mp3",
      "seconds": 12.042
    },
    "paper": {
      "src": "audio/sfx/paper.mp3",
      "seconds": 1.829
    },
    "pen": {
      "src": "audio/sfx/pen.mp3",
      "seconds": 5.538
    },
    "room-tone": {
      "src": "audio/sfx/room-tone.mp3",
      "seconds": 62.276
    }
  }
};
