// Scans public/audio, measures every file and writes src/data/audio-manifest.ts.
// Recorded narration lines then set the length of their cue, so scenes,
// subtitles and animations follow the audio.
//
//   public/audio/voiceover/<sceneId>/<cueId>.<ext>   one narration line
//   public/audio/music/<slotId>.<ext>                one music slot
//   public/audio/sfx/<sfxId>.<ext>                   one sound effect
//
// Run with: npm run sync:audio

import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { MUSIC, SFX } from "../src/data/assets.ts";
import type { AudioFile, AudioManifest } from "../src/data/audio-manifest.ts";
import { STORY } from "../src/data/story.ts";

const PUBLIC = "public";
const EXTENSIONS = [".mp3", ".wav", ".m4a", ".aac", ".ogg"];
const REMOTION = path.join("node_modules", ".bin", "remotion");

const measure = (file: string): number => {
  const out = execFileSync(REMOTION, ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", file], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  });
  const seconds = parseFloat(out.trim().split("\n").pop() ?? "");
  if (!Number.isFinite(seconds)) {
    throw new Error(`Could not read the duration of ${file}`);
  }
  return Math.round(seconds * 1000) / 1000;
};

const audioIn = (dir: string) =>
  existsSync(dir)
    ? readdirSync(dir).filter((f) => EXTENSIONS.includes(path.extname(f).toLowerCase()) && statSync(path.join(dir, f)).isFile())
    : [];

const entry = (file: string): AudioFile => ({ src: path.relative(PUBLIC, file).split(path.sep).join("/"), seconds: measure(file) });

const manifest: AudioManifest = { lines: {}, music: {}, sfx: {} };
const warnings: string[] = [];
const missing: string[] = [];

for (const scene of STORY) {
  const dir = path.join(PUBLIC, "audio", "voiceover", scene.id);
  const ids = new Set(scene.cues.map((c) => c.id));
  for (const file of audioIn(dir)) {
    const id = path.parse(file).name;
    if (ids.has(id)) {
      manifest.lines[`${scene.id}/${id}`] = entry(path.join(dir, file));
    } else {
      warnings.push(`voiceover/${scene.id}/${file}: no line called "${id}"`);
    }
  }
  for (const cue of scene.cues) {
    if (!manifest.lines[`${scene.id}/${cue.id}`]) {
      missing.push(`${scene.id}/${cue.id}`);
    }
  }
}

const register = (kind: "music" | "sfx", ids: Set<string>) => {
  const dir = path.join(PUBLIC, "audio", kind);
  for (const file of audioIn(dir)) {
    const id = path.parse(file).name;
    if (ids.has(id)) {
      manifest[kind][id] = entry(path.join(dir, file));
    } else {
      warnings.push(`${kind}/${file}: not used by any ${kind === "music" ? "music slot" : "sound cue"}`);
    }
  }
  for (const id of ids) {
    if (!manifest[kind][id]) {
      warnings.push(`${kind}: no file for "${id}" (slot stays silent)`);
    }
  }
};
register("music", new Set(MUSIC.slots.map((s) => s.id)));
register("sfx", new Set(SFX.map((s) => s.sound)));

const sorted = <T,>(o: Record<string, T>) => Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));
const body = JSON.stringify({ lines: manifest.lines, music: sorted(manifest.music), sfx: sorted(manifest.sfx) }, null, 2);
writeFileSync(
  path.join("src", "data", "audio-manifest.ts"),
  `// Generated by \`npm run sync:audio\`. Do not edit by hand.

export type AudioFile = { src: string; seconds: number };
export type AudioManifest = {
  lines: Record<string, AudioFile>;
  music: Record<string, AudioFile>;
  sfx: Record<string, AudioFile>;
};

export const AUDIO_MANIFEST: AudioManifest = ${body};
`,
);

const lineSeconds = Object.values(manifest.lines).reduce((s, f) => s + f.seconds, 0);
console.log(`narration: ${Object.keys(manifest.lines).length} lines (${lineSeconds.toFixed(1)} s), ${missing.length} missing`);
console.log(`music: ${Object.keys(manifest.music).length}/${MUSIC.slots.length} slots · sfx: ${Object.keys(manifest.sfx).length} sounds`);
for (const w of warnings) console.log(`  ! ${w}`);

const { TOTAL_FRAMES, SCENES } = await import(`../src/data/timing.ts?${Date.now()}`);
const mmss = (f: number) => `${Math.floor(f / 30 / 60)}:${String(Math.floor(f / 30) % 60).padStart(2, "0")}`;
console.log(`film length: ${mmss(TOTAL_FRAMES)} (${TOTAL_FRAMES} frames)`);
for (const s of SCENES) console.log(`  ${String(s.number).padStart(2)} ${s.id.padEnd(16)} ${mmss(s.from)}  ${(s.durationInFrames / 30).toFixed(1)} s`);
