// Scans public/audio for voice-over and music files, measures each one and
// writes src/config/audio-manifest.ts. Recorded narration lines then set the
// length of their cue, so scenes, subtitles and animations follow the audio.
//
//   public/audio/voiceover/<sceneId>/<cueId>.<ext>   one narration line
//   public/audio/voiceover/<sceneId>.<ext>           one whole scene
//   public/audio/music/<slotId>.<ext>                one music slot
//
// Run with: npm run sync:audio

import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ASSETS } from "../src/config/assets.ts";
import type { AudioFile, AudioManifest } from "../src/config/audio-manifest.ts";
import { SCRIPT } from "../src/config/narration.ts";

const PUBLIC = "public";
const EXTENSIONS = [".mp3", ".wav", ".m4a", ".aac", ".ogg"];
const REMOTION = path.join("node_modules", ".bin", "remotion");

const measure = (file: string): number => {
  const out = execFileSync(REMOTION, ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", file], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  });
  const seconds = parseFloat(out.trim().split("\n").pop() ?? "");
  if (!Number.isFinite(seconds)) {
    throw new Error(`Could not read the duration of ${file}`);
  }
  return Math.round(seconds * 1000) / 1000;
};

const audioIn = (dir: string) =>
  existsSync(dir)
    ? readdirSync(dir).filter((f) => EXTENSIONS.includes(path.extname(f).toLowerCase()) && statSync(path.join(dir, f)).isFile())
    : [];

const entry = (file: string): AudioFile => ({
  src: path.relative(PUBLIC, file).split(path.sep).join("/"),
  seconds: measure(file),
});

const manifest: AudioManifest = { lines: {}, scenes: {}, music: {} };
const warnings: string[] = [];
const voDir = path.join(PUBLIC, "audio", "voiceover");
const musicDir = path.join(PUBLIC, "audio", "music");
const sceneIds = new Set(SCRIPT.map((s) => s.id));

for (const file of audioIn(voDir)) {
  const id = path.parse(file).name;
  if (sceneIds.has(id as never)) {
    manifest.scenes[id] = entry(path.join(voDir, file));
  } else {
    warnings.push(`voiceover/${file}: no scene called "${id}"`);
  }
}

for (const scene of SCRIPT) {
  const dir = path.join(voDir, scene.id);
  const cueIds = new Set(scene.cues.map((c) => c.id));
  for (const file of audioIn(dir)) {
    const id = path.parse(file).name;
    if (cueIds.has(id)) {
      manifest.lines[`${scene.id}/${id}`] = entry(path.join(dir, file));
    } else {
      warnings.push(`voiceover/${scene.id}/${file}: no cue called "${id}" in scene "${scene.id}"`);
    }
  }
  if (manifest.scenes[scene.id] && scene.cues.some((c) => manifest.lines[`${scene.id}/${c.id}`])) {
    warnings.push(`${scene.id}: has both a whole-scene file and per-line files; both will play`);
  }
}

const slotIds = new Set(ASSETS.music.slots.map((s) => s.id));
for (const file of audioIn(musicDir)) {
  const id = path.parse(file).name;
  if (slotIds.has(id)) {
    manifest.music[id] = entry(path.join(musicDir, file));
  } else {
    warnings.push(`music/${file}: no music slot called "${id}" (slots: ${[...slotIds].join(", ")})`);
  }
}

const body = JSON.stringify(manifest, null, 2);
writeFileSync(
  path.join("src", "config", "audio-manifest.ts"),
  `// GENERATED by \`npm run sync:audio\`. Do not edit by hand.
// Lists the audio files found in public/audio and their measured lengths.

export type AudioFile = { src: string; seconds: number };

export type AudioManifest = {
  // "<sceneId>/<cueId>": one recorded narration line
  lines: Record<string, AudioFile>;
  // "<sceneId>": one recording covering a whole scene
  scenes: Record<string, AudioFile>;
  // "<slotId>": background music for a music slot
  music: Record<string, AudioFile>;
};

export const AUDIO_MANIFEST: AudioManifest = ${body};
`,
);

// Load the timeline fresh so it picks up the new measurements.
const { SCENES, TOTAL_FRAMES, timecode } = await import(`../src/config/timing.ts?${Date.now()}`);
const totalLines = SCRIPT.reduce((n, s) => n + s.cues.length, 0);
const lineCount = Object.keys(manifest.lines).length;

console.log(`Voice-over lines: ${lineCount}/${totalLines}`);
for (const scene of SCRIPT) {
  const missing = scene.cues.filter((c) => !manifest.lines[`${scene.id}/${c.id}`]).map((c) => c.id);
  const whole = manifest.scenes[scene.id] ? " (+ whole-scene file)" : "";
  console.log(`  ${scene.id.padEnd(14)} ${scene.cues.length - missing.length}/${scene.cues.length}${whole}${missing.length && missing.length < scene.cues.length ? `  missing: ${missing.join(", ")}` : ""}`);
}
console.log(`Music slots: ${ASSETS.music.slots.map((s) => `${s.id} ${manifest.music[s.id] ? "✓" : "empty"}`).join(", ")}`);
console.log(`Video length: ${timecode(TOTAL_FRAMES)} (${SCENES.length} scenes)`);
if (TOTAL_FRAMES / 30 > 360) {
  warnings.push("video is now longer than 6 minutes; trim lines or reduce pauses in narration.ts");
}
for (const w of warnings) {
  console.warn(`Warning: ${w}`);
}
