// Generated by `npm run sync:audio`. Do not edit by hand.

export type AudioFile = { src: string; seconds: number };
export type AudioManifest = {
  lines: Record<string, AudioFile>;
  music: Record<string, AudioFile>;
  sfx: Record<string, AudioFile>;
};

export const AUDIO_MANIFEST: AudioManifest = {
  "lines": {
    "opening/atlantic": {
      "src": "audio/voiceover/opening/atlantic.mp3",
      "seconds": 2.403
    },
    "opening/contact": {
      "src": "audio/voiceover/opening/contact.mp3",
      "seconds": 3.657
    },
    "opening/flightNo": {
      "src": "audio/voiceover/opening/flightNo.mp3",
      "seconds": 3.213
    },
    "opening/hours": {
      "src": "audio/voiceover/opening/hours.mp3",
      "seconds": 2.116
    },
    "opening/mystery": {
      "src": "audio/voiceover/opening/mystery.mp3",
      "seconds": 6.583
    },
    "opening/night": {
      "src": "audio/voiceover/opening/night.mp3",
      "seconds": 2.638
    },
    "opening/normal": {
      "src": "audio/voiceover/opening/normal.mp3",
      "seconds": 3.788
    },
    "opening/people": {
      "src": "audio/voiceover/opening/people.mp3",
      "seconds": 4.545
    },
    "opening/takeoff": {
      "src": "audio/voiceover/opening/takeoff.mp3",
      "seconds": 5.433
    },
    "opening/total": {
      "src": "audio/voiceover/opening/total.mp3",
      "seconds": 2.299
    },
    "normalFlight/a330": {
      "src": "audio/voiceover/normalFlight/a330.mp3",
      "seconds": 5.12
    },
    "normalFlight/altitude": {
      "src": "audio/voiceover/normalFlight/altitude.mp3",
      "seconds": 2.9
    },
    "normalFlight/deviate": {
      "src": "audio/voiceover/normalFlight/deviate.mp3",
      "seconds": 6.635
    },
    "normalFlight/nothing": {
      "src": "audio/voiceover/normalFlight/nothing.mp3",
      "seconds": 8.908
    },
    "normalFlight/paris": {
      "src": "audio/voiceover/normalFlight/paris.mp3",
      "seconds": 1.437
    },
    "normalFlight/route": {
      "src": "audio/voiceover/normalFlight/route.mp3",
      "seconds": 8.725
    },
    "normalFlight/sea": {
      "src": "audio/voiceover/normalFlight/sea.mp3",
      "seconds": 2.926
    },
    "normalFlight/sky": {
      "src": "audio/voiceover/normalFlight/sky.mp3",
      "seconds": 2.011
    },
    "normalFlight/until": {
      "src": "audio/voiceover/normalFlight/until.mp3",
      "seconds": 1.306
    },
    "normalFlight/weather": {
      "src": "audio/voiceover/normalFlight/weather.mp3",
      "seconds": 4.728
    },
    "pitotProblem/autopilot": {
      "src": "audio/voiceover/pitotProblem/autopilot.mp3",
      "seconds": 2.429
    },
    "pitotProblem/change": {
      "src": "audio/voiceover/pitotProblem/change.mp3",
      "seconds": 3.161
    },
    "pitotProblem/crystals": {
      "src": "audio/voiceover/pitotProblem/crystals.mp3",
      "seconds": 7.001
    },
    "pitotProblem/inconsistent": {
      "src": "audio/voiceover/pitotProblem/inconsistent.mp3",
      "seconds": 5.329
    },
    "pitotProblem/info": {
      "src": "audio/voiceover/pitotProblem/info.mp3",
      "seconds": 5.355
    },
    "pitotProblem/law": {
      "src": "audio/voiceover/pitotProblem/law.mp3",
      "seconds": 3.396
    },
    "pitotProblem/manual": {
      "src": "audio/voiceover/pitotProblem/manual.mp3",
      "seconds": 3.84
    },
    "pitotProblem/probes": {
      "src": "audio/voiceover/pitotProblem/probes.mp3",
      "seconds": 4.676
    },
    "pitotProblem/time": {
      "src": "audio/voiceover/pitotProblem/time.mp3",
      "seconds": 3.396
    },
    "pitotProblem/unreliable": {
      "src": "audio/voiceover/pitotProblem/unreliable.mp3",
      "seconds": 3.213
    },
    "pitotProblem/what": {
      "src": "audio/voiceover/pitotProblem/what.mp3",
      "seconds": 6.113
    },
    "climb/altitude": {
      "src": "audio/voiceover/climb/altitude.mp3",
      "seconds": 2.717
    },
    "climb/contradictory": {
      "src": "audio/voiceover/climb/contradictory.mp3",
      "seconds": 5.042
    },
    "climb/difficult": {
      "src": "audio/voiceover/climb/difficult.mp3",
      "seconds": 2.926
    },
    "climb/down": {
      "src": "audio/voiceover/climb/down.mp3",
      "seconds": 2.952
    },
    "climb/envelope": {
      "src": "audio/voiceover/climb/envelope.mp3",
      "seconds": 5.512
    },
    "climb/important": {
      "src": "audio/voiceover/climb/important.mp3",
      "seconds": 8.124
    },
    "climb/nose": {
      "src": "audio/voiceover/climb/nose.mp3",
      "seconds": 2.691
    },
    "climb/speed": {
      "src": "audio/voiceover/climb/speed.mp3",
      "seconds": 3.579
    },
    "climb/then": {
      "src": "audio/voiceover/climb/then.mp3",
      "seconds": 0.888
    },
    "climb/up": {
      "src": "audio/voiceover/climb/up.mp3",
      "seconds": 2.168
    },
    "climb/warning": {
      "src": "audio/voiceover/climb/warning.mp3",
      "seconds": 2.664
    },
    "stall/andThen": {
      "src": "audio/voiceover/stall/andThen.mp3",
      "seconds": 0.888
    },
    "stall/aoa": {
      "src": "audio/voiceover/stall/aoa.mp3",
      "seconds": 3.5
    },
    "stall/date": {
      "src": "audio/voiceover/stall/date.mp3",
      "seconds": 2.168
    },
    "stall/falling": {
      "src": "audio/voiceover/stall/falling.mp3",
      "seconds": 5.512
    },
    "stall/impact": {
      "src": "audio/voiceover/stall/impact.mp3",
      "seconds": 4.441
    },
    "stall/meaning": {
      "src": "audio/voiceover/stall/meaning.mp3",
      "seconds": 5.695
    },
    "stall/minutes": {
      "src": "audio/voiceover/stall/minutes.mp3",
      "seconds": 1.515
    },
    "stall/notEngines": {
      "src": "audio/voiceover/stall/notEngines.mp3",
      "seconds": 3.265
    },
    "stall/notRecognised": {
      "src": "audio/voiceover/stall/notRecognised.mp3",
      "seconds": 5.146
    },
    "stall/reaching": {
      "src": "audio/voiceover/stall/reaching.mp3",
      "seconds": 3.056
    },
    "stall/time": {
      "src": "audio/voiceover/stall/time.mp3",
      "seconds": 4.232
    },
    "disappearance/ended": {
      "src": "audio/voiceover/disappearance/ended.mp3",
      "seconds": 4.389
    },
    "disappearance/important": {
      "src": "audio/voiceover/disappearance/important.mp3",
      "seconds": 2.325
    },
    "disappearance/lastContact": {
      "src": "audio/voiceover/disappearance/lastContact.mp3",
      "seconds": 6.661
    },
    "disappearance/location": {
      "src": "audio/voiceover/disappearance/location.mp3",
      "seconds": 3.422
    },
    "disappearance/recorders": {
      "src": "audio/voiceover/disappearance/recorders.mp3",
      "seconds": 4.075
    },
    "disappearance/searchBegins": {
      "src": "audio/voiceover/disappearance/searchBegins.mp3",
      "seconds": 4.206
    },
    "disappearance/unknown": {
      "src": "audio/voiceover/disappearance/unknown.mp3",
      "seconds": 3.944
    },
    "disappearance/vast": {
      "src": "audio/voiceover/disappearance/vast.mp3",
      "seconds": 1.646
    },
    "search/area": {
      "src": "audio/voiceover/search/area.mp3",
      "seconds": 4.963
    },
    "search/debris": {
      "src": "audio/voiceover/search/debris.mp3",
      "seconds": 2.795
    },
    "search/depth": {
      "src": "audio/voiceover/search/depth.mp3",
      "seconds": 5.198
    },
    "search/hard": {
      "src": "audio/voiceover/search/hard.mp3",
      "seconds": 3.291
    },
    "search/months": {
      "src": "audio/voiceover/search/months.mp3",
      "seconds": 2.534
    },
    "search/notFound": {
      "src": "audio/voiceover/search/notFound.mp3",
      "seconds": 4.624
    },
    "search/notSurface": {
      "src": "audio/voiceover/search/notSurface.mp3",
      "seconds": 4.206
    },
    "twoYears/april": {
      "src": "audio/voiceover/twoYears/april.mp3",
      "seconds": 2.743
    },
    "twoYears/continued": {
      "src": "audio/voiceover/twoYears/continued.mp3",
      "seconds": 3.683
    },
    "twoYears/discovery": {
      "src": "audio/voiceover/twoYears/discovery.mp3",
      "seconds": 2.482
    },
    "twoYears/missing": {
      "src": "audio/voiceover/twoYears/missing.mp3",
      "seconds": 4.728
    },
    "twoYears/recorders": {
      "src": "audio/voiceover/twoYears/recorders.mp3",
      "seconds": 1.567
    },
    "twoYears/recovered": {
      "src": "audio/voiceover/twoYears/recovered.mp3",
      "seconds": 7.393
    },
    "twoYears/theories": {
      "src": "audio/voiceover/twoYears/theories.mp3",
      "seconds": 2.09
    },
    "twoYears/wreckage": {
      "src": "audio/voiceover/twoYears/wreckage.mp3",
      "seconds": 3.814
    },
    "blackBox/c1": {
      "src": "audio/voiceover/blackBox/c1.mp3",
      "seconds": 5.616
    },
    "blackBox/c2": {
      "src": "audio/voiceover/blackBox/c2.mp3",
      "seconds": 2.325
    },
    "blackBox/c3": {
      "src": "audio/voiceover/blackBox/c3.mp3",
      "seconds": 4.833
    },
    "blackBox/c4": {
      "src": "audio/voiceover/blackBox/c4.mp3",
      "seconds": 2.325
    },
    "blackBox/c5": {
      "src": "audio/voiceover/blackBox/c5.mp3",
      "seconds": 5.851
    },
    "blackBox/chain": {
      "src": "audio/voiceover/blackBox/chain.mp3",
      "seconds": 4.31
    },
    "blackBox/cvr": {
      "src": "audio/voiceover/blackBox/cvr.mp3",
      "seconds": 4.728
    },
    "blackBox/fdr": {
      "src": "audio/voiceover/blackBox/fdr.mp3",
      "seconds": 5.616
    },
    "blackBox/now": {
      "src": "audio/voiceover/blackBox/now.mp3",
      "seconds": 5.538
    },
    "blackBox/report": {
      "src": "audio/voiceover/blackBox/report.mp3",
      "seconds": 6.296
    },
    "realMystery/chain": {
      "src": "audio/voiceover/realMystery/chain.mp3",
      "seconds": 3.736
    },
    "realMystery/computers": {
      "src": "audio/voiceover/realMystery/computers.mp3",
      "seconds": 2.534
    },
    "realMystery/f1": {
      "src": "audio/voiceover/realMystery/f1.mp3",
      "seconds": 1.933
    },
    "realMystery/f2": {
      "src": "audio/voiceover/realMystery/f2.mp3",
      "seconds": 2.429
    },
    "realMystery/f3": {
      "src": "audio/voiceover/realMystery/f3.mp3",
      "seconds": 2.847
    },
    "realMystery/f4": {
      "src": "audio/voiceover/realMystery/f4.mp3",
      "seconds": 4.023
    },
    "realMystery/f5": {
      "src": "audio/voiceover/realMystery/f5.mp3",
      "seconds": 2.847
    },
    "realMystery/how": {
      "src": "audio/voiceover/realMystery/how.mp3",
      "seconds": 2.821
    },
    "realMystery/modern": {
      "src": "audio/voiceover/realMystery/modern.mp3",
      "seconds": 2.56
    },
    "realMystery/notOne": {
      "src": "audio/voiceover/realMystery/notOne.mp3",
      "seconds": 4.728
    },
    "realMystery/notOnly": {
      "src": "audio/voiceover/realMystery/notOnly.mp3",
      "seconds": 6.4
    },
    "realMystery/pilots": {
      "src": "audio/voiceover/realMystery/pilots.mp3",
      "seconds": 2.194
    },
    "realMystery/question": {
      "src": "audio/voiceover/realMystery/question.mp3",
      "seconds": 1.515
    },
    "realMystery/solved": {
      "src": "audio/voiceover/realMystery/solved.mp3",
      "seconds": 4.545
    },
    "realMystery/systems": {
      "src": "audio/voiceover/realMystery/systems.mp3",
      "seconds": 2.586
    },
    "realMystery/yes": {
      "src": "audio/voiceover/realMystery/yes.mp3",
      "seconds": 0.731
    },
    "lessons/case": {
      "src": "audio/voiceover/lessons/case.mp3",
      "seconds": 7.314
    },
    "lessons/humans": {
      "src": "audio/voiceover/lessons/humans.mp3",
      "seconds": 7.419
    },
    "lessons/industry": {
      "src": "audio/voiceover/lessons/industry.mp3",
      "seconds": 5.956
    },
    "lessons/lesson": {
      "src": "audio/voiceover/lessons/lesson.mp3",
      "seconds": 3.318
    },
    "lessons/probes": {
      "src": "audio/voiceover/lessons/probes.mp3",
      "seconds": 3.605
    },
    "lessons/simulator": {
      "src": "audio/voiceover/lessons/simulator.mp3",
      "seconds": 3.762
    },
    "lessons/technology": {
      "src": "audio/voiceover/lessons/technology.mp3",
      "seconds": 2.926
    },
    "lessons/training": {
      "src": "audio/voiceover/lessons/training.mp3",
      "seconds": 7.549
    },
    "lessons/unreliable": {
      "src": "audio/voiceover/lessons/unreliable.mp3",
      "seconds": 2.952
    },
    "ending/answer": {
      "src": "audio/voiceover/ending/answer.mp3",
      "seconds": 1.463
    },
    "ending/chain": {
      "src": "audio/voiceover/ending/chain.mp3",
      "seconds": 8.829
    },
    "ending/crossing": {
      "src": "audio/voiceover/ending/crossing.mp3",
      "seconds": 4.258
    },
    "ending/decisions": {
      "src": "audio/voiceover/ending/decisions.mp3",
      "seconds": 3.866
    },
    "ending/lessons": {
      "src": "audio/voiceover/ending/lessons.mp3",
      "seconds": 5.799
    },
    "ending/lost": {
      "src": "audio/voiceover/ending/lost.mp3",
      "seconds": 3.291
    },
    "ending/minutes": {
      "src": "audio/voiceover/ending/minutes.mp3",
      "seconds": 1.515
    },
    "ending/night": {
      "src": "audio/voiceover/ending/night.mp3",
      "seconds": 2.456
    },
    "ending/notPlace": {
      "src": "audio/voiceover/ending/notPlace.mp3",
      "seconds": 3.161
    },
    "ending/seconds": {
      "src": "audio/voiceover/ending/seconds.mp3",
      "seconds": 1.411
    },
    "ending/sensor": {
      "src": "audio/voiceover/ending/sensor.mp3",
      "seconds": 1.567
    },
    "ending/sometimes": {
      "src": "audio/voiceover/ending/sometimes.mp3",
      "seconds": 3.056
    }
  },
  "music": {
    "cruise": {
      "src": "audio/music/cruise.mp3",
      "seconds": 108.147
    },
    "deep": {
      "src": "audio/music/deep.mp3",
      "seconds": 74.971
    },
    "discovery": {
      "src": "audio/music/discovery.mp3",
      "seconds": 92.918
    },
    "ending": {
      "src": "audio/music/ending.mp3",
      "seconds": 61.727
    },
    "opening": {
      "src": "audio/music/opening.mp3",
      "seconds": 50.051
    },
    "reflection": {
      "src": "audio/music/reflection.mp3",
      "seconds": 112.248
    },
    "tension": {
      "src": "audio/music/tension.mp3",
      "seconds": 74.632
    }
  },
  "sfx": {
    "airport": {
      "src": "audio/sfx/airport.mp3",
      "seconds": 50.051
    },
    "ap-disconnect": {
      "src": "audio/sfx/ap-disconnect.mp3",
      "seconds": 3.03
    },
    "cabin": {
      "src": "audio/sfx/cabin.mp3",
      "seconds": 52.297
    },
    "chime": {
      "src": "audio/sfx/chime.mp3",
      "seconds": 2.038
    },
    "cockpit": {
      "src": "audio/sfx/cockpit.mp3",
      "seconds": 58.044
    },
    "data": {
      "src": "audio/sfx/data.mp3",
      "seconds": 9.038
    },
    "ice": {
      "src": "audio/sfx/ice.mp3",
      "seconds": 9.038
    },
    "radar": {
      "src": "audio/sfx/radar.mp3",
      "seconds": 6.034
    },
    "radio": {
      "src": "audio/sfx/radio.mp3",
      "seconds": 4.049
    },
    "sea": {
      "src": "audio/sfx/sea.mp3",
      "seconds": 16.039
    },
    "sonar": {
      "src": "audio/sfx/sonar.mp3",
      "seconds": 13.035
    },
    "stall-warning": {
      "src": "audio/sfx/stall-warning.mp3",
      "seconds": 10.031
    },
    "takeoff": {
      "src": "audio/sfx/takeoff.mp3",
      "seconds": 16.039
    },
    "underwater": {
      "src": "audio/sfx/underwater.mp3",
      "seconds": 16.039
    },
    "weather": {
      "src": "audio/sfx/weather.mp3",
      "seconds": 14.028
    }
  }
};
